// <auto-generated />
using HW_4_Top_10_CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW_4_Top_10_CRUD.Migrations
{
    [DbContext(typeof(TenMoviesContext))]
    [Migration("20240622120754_StartTenMovies")]
    partial class StartTenMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");
#pragma warning restore 612, 618
        }
    }
}
