//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HW_7_MusicPortal.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш аккаунт не подтвкрждён....
        /// </summary>
        public static string AccountNotConfirm {
            get {
                return ResourceManager.GetString("AccountNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить Жанр.
        /// </summary>
        public static string AddGenre {
            get {
                return ResourceManager.GetString("AddGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить трек.
        /// </summary>
        public static string AddTrack {
            get {
                return ResourceManager.GetString("AddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом уже есть.
        /// </summary>
        public static string AlbumHasAlready {
            get {
                return ResourceManager.GetString("AlbumHasAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбом только в жанр-&gt; Категория -&gt; Исполнитель.
        /// </summary>
        public static string AlbumOnly {
            get {
                return ResourceManager.GetString("AlbumOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Альбомы.
        /// </summary>
        public static string AllAlbum {
            get {
                return ResourceManager.GetString("AllAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанры.
        /// </summary>
        public static string AllGenre {
            get {
                return ResourceManager.GetString("AllGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители.
        /// </summary>
        public static string AllPerformer {
            get {
                return ResourceManager.GetString("AllPerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треки.
        /// </summary>
        public static string AllTrack {
            get {
                return ResourceManager.GetString("AllTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокировать.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория уже eсть.
        /// </summary>
        public static string CategoryHasAlready {
            get {
                return ResourceManager.GetString("CategoryHasAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорию добавить можно только в жанр.
        /// </summary>
        public static string CategoryOnlyInGnere {
            get {
                return ResourceManager.GetString("CategoryOnlyInGnere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин 3 буквы 2 цифры, мин 10 макс 20 символов.
        /// </summary>
        public static string CheckLogin {
            get {
                return ResourceManager.GetString("CheckLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор Альбома.
        /// </summary>
        public static string ChoiseAlbum {
            get {
                return ResourceManager.GetString("ChoiseAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор Категории.
        /// </summary>
        public static string ChoiseCategoty {
            get {
                return ResourceManager.GetString("ChoiseCategoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор Жанра.
        /// </summary>
        public static string ChoiseGenre {
            get {
                return ResourceManager.GetString("ChoiseGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор  исполнителя.
        /// </summary>
        public static string ChoisePerformer {
            get {
                return ResourceManager.GetString("ChoisePerformer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать Жанр.
        /// </summary>
        public static string EditGenre {
            get {
                return ResourceManager.GetString("EditGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать Трек.
        /// </summary>
        public static string EditTrack {
            get {
                return ResourceManager.GetString("EditTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в систему.
        /// </summary>
        public static string Enter_system {
            get {
                return ResourceManager.GetString("Enter system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр Уже eсть.
        /// </summary>
        public static string GenreHasAlready {
            get {
                return ResourceManager.GetString("GenreHasAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от 3 до 10 символов.
        /// </summary>
        public static string GenreSimbol {
            get {
                return ResourceManager.GetString("GenreSimbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домой.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы вошли как.
        /// </summary>
        public static string Logged {
            get {
                return ResourceManager.GetString("Logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизоваться.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войдите или зарегистрируйтесь.
        /// </summary>
        public static string MessageGuest {
            get {
                return ResourceManager.GetString("MessageGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музыка.
        /// </summary>
        public static string MusicMenegment {
            get {
                return ResourceManager.GetString("MusicMenegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Nick {
            get {
                return ResourceManager.GetString("Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такое имя уже используется.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель.
        /// </summary>
        public static string Performer {
            get {
                return ResourceManager.GetString("Performer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель уже eсть.
        /// </summary>
        public static string PerformerHasAlready {
            get {
                return ResourceManager.GetString("PerformerHasAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель добавить можно   только в категории.
        /// </summary>
        public static string PerformerOnlyInCategory {
            get {
                return ResourceManager.GetString("PerformerOnlyInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от 3 до 20 символов.
        /// </summary>
        public static string PerformerSimbol {
            get {
                return ResourceManager.GetString("PerformerSimbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процессе.
        /// </summary>
        public static string ProccesMessage {
            get {
                return ResourceManager.GetString("ProccesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Registr {
            get {
                return ResourceManager.GetString("Registr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string ToConfirm {
            get {
                return ResourceManager.GetString("ToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбириту все пункты.
        /// </summary>
        public static string TrackAdd {
            get {
                return ResourceManager.GetString("TrackAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить композицию.
        /// </summary>
        public static string UploadComposition {
            get {
                return ResourceManager.GetString("UploadComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string UserMenegment {
            get {
                return ResourceManager.GetString("UserMenegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
